/* vxi11_python.c
   Adapted for a python interface from vxi11_cmd.cc by khaho.
   Copyright below is kept just to show that adaptation is legal
*/
   

/* vxi11_cmd.c
 * Copyright (C) 2006 Steve D. Sharples
 *
 * A simple interactive utility that allows you to send commands and queries to
	 * a device enabled with the VXI11 RPC ethernet protocol. Uses the files
 * generated by rpcgen vxi11.x, and the vxi11_user.h user libraries.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 * 
 * The author's email address is steve.sharples@nottingham.ac.uk
 */

#include "vxi11_1.10/vxi11_user.h"
#include "vxi11_python.h"

#define MAX_RESP 20*1024*1024

char cmd_buffer[MAX_RESP];

CLINK *clink;

int open(char *device_ip, char *device_name) 
{
        clink = new CLINK;
	return vxi11_open_device(device_ip, clink, device_name);
}

int cmd(char *cmd)
{
	/* maybe not the first bytes of buffer, same access needed */
	long long *ret = (long long *)cmd_buffer;

	if (vxi11_send(clink, cmd) < 0) return 0;
	if (strstr(cmd, "?") != 0) {
		return vxi11_receive(clink, (char *)ret, MAX_RESP);
	}
	return 0;
}

long long resp(int index)
{
	/* maybe not the first bytes of buffer, same access needed */
	long long *ret = (long long *)cmd_buffer;
        return ret[index];
}

int close(char *device_ip)
{
	vxi11_close_device(device_ip, clink);
	return 0;
}
