/* vxi11_python.c
   Adapted for a python interface from vxi11_cmd.cc by khaho.
   Copyright below is kept just to show that adaptation is legal
*/
 

/* vxi11_cmd.c
 * Copyright (C) 2006 Steve D. Sharples
 *
 * A simple interactive utility that allows you to send commands and queries to
	 * a device enabled with the VXI11 RPC ethernet protocol. Uses the files
 * generated by rpcgen vxi11.x, and the vxi11_user.h user libraries.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * The author's email address is steve.sharples@nottingham.ac.uk
 */

#include "vxi11_1.10/vxi11_user.h"
#include "vxi11cc.h"

PLINK *iconnect(char *device_ip, long buffer_size, char *device_name)
{
	char *cp;
	PLINK *plink;

	if (device_ip == NULL) return NULL;

	cp  = (char *)malloc(buffer_size);
	if (cp == NULL) return NULL;

	plink = new PLINK;

	plink->buffer_size = buffer_size;
	plink->buffer = cp;

	plink->clink = new CLINK;

	plink->device_ip = (char *)malloc(120);
	strncpy(plink->device_ip, device_ip, 100);

	plink->device_name = (char *)malloc(120);
	strncpy(plink->device_name, device_name, 100);

	if (vxi11_open_device(plink->device_ip, plink->clink, plink->device_name) != 0) {
		free(plink->buffer);
		free(plink->device_name);
		free(plink->device_ip);
		delete plink->clink;
		delete plink;
		return NULL;
	}
	return plink;
}

int icommand(PLINK *plink, char *cmd, long timeout_ms)
{
	if (vxi11_send(plink->clink, cmd) < 0) return 0;
	if (strstr(cmd, "?") != 0) {
		return vxi11_receive(plink->clink, plink->buffer, plink->buffer_size, timeout_ms);
	}
	return 0;
}

long long iresponse(PLINK *plink, int index)
{
	long long *ret = (long long *)plink->buffer;
        return ret[index];
}

int idisconnect(PLINK *plink)
{
	vxi11_close_device(plink->device_ip, plink->clink);
	free(plink->buffer);
	free(plink->device_name);
	free(plink->device_ip);
	delete plink->clink;
	delete plink;

	return 0;
}
